# Generated by Django 5.0.7 on 2024-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(
                default="FR00RCPQQ5M5UV", max_length=34, unique=True
            ),
        ),
    ]
