# Generated by Django 5.0.7 on 2024-08-01 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0002_bankaccount_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(
                default="FR00YUGF8FURC7", max_length=34, unique=True
            ),
        ),
    ]
