# Generated by Django 5.0.7 on 2024-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0003_bankaccount_date_alter_bankaccount_iban"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(
                default="FR00O1MPCIVNVN", max_length=34, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdraw")],
                max_length=10,
            ),
        ),
    ]
